[general]
import = ["/home/eltorrero/.config/alacritty/dracula.toml"]
working_directory = "/home/eltorrero"

[font]
size = 12.0
normal = { family = "JetBrainsMono NF" }

[keyboard]
bindings = [
    { key = "N", mods = "Control", action = "CreateNewWindow" },
    { key = "F11", action = "ToggleFullscreen" },
    { key = "H", mods = "Alt", action = "Minimize" }
]

[window]
dynamic_title = false
dimensions = { columns = 160, lines = 42 }
padding = { x = 6, y = 6 }
position = { x = 200, y = 120 }
# decorations = "None"
# startup_mode = "Fullscreen"

